// sk83 - ReXGlue Recompiled Project
// Generated by: rexglue init
//
// This file is SDK-managed. Customizations go in virtual hook overrides.
// Running 'rexglue migrate' will overwrite this file.

#include "generated/sk83_init.h"

#include <rex/rex_app.h>

#include <filesystem>

class Sk83App : public rex::ReXApp {
 public:
  using rex::ReXApp::ReXApp;

  static std::unique_ptr<rex::ui::WindowedApp> Create(
      rex::ui::WindowedAppContext& ctx) {
    return std::unique_ptr<Sk83App>(new Sk83App(ctx, "sk83", PPCImageConfig));
  }

 protected:
  void OnConfigurePaths(rex::PathConfig& paths) override {
    const auto project_root = std::filesystem::path(__FILE__).parent_path().parent_path();
    const auto assets = project_root / "assets";
    if (std::filesystem::exists(assets)) {
      paths.game_data_root = assets;
    }
  }
};

REX_DEFINE_APP(sk83, Sk83App::Create)
